export enum Category {
    HOBBIES = 'HOBBIES',
    WELLBEING = 'WELLBEING',
    MOVINGAROUND = 'MOVINGAROUND',
    HOLIDAYTRIPS = 'HOLIDAYTRIPS',
    OTHER = 'OTHER',
    PAYCHECK = 'PAYCHECK',
    FOOD = 'FOOD',
    ELECTRONICSERVICES = 'ELECTRONICSERVICES',
    CLOTHING = 'CLOTHING',
    INSURANCES = 'INSURANCES',
    ENTERTAINMENT = 'ENTERTAINMENT',
}
